config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  resources :companies do
    resources :reviews, only: [:new, :create, :show, :destroy]
     
  end 
  
  resources :reviews do
    resources :thanks, only: [:new, :create]
  end

  resources :reviews do
    resources :comments, only: [:new, :create]
  end

  resources :user_companies

  resources :users do 
    resources :user_companies, only: [:show, :new, :create]
  end 

  resources :users do 
    resources :profiles, only: [:show, :new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController<ApplicationController

    def new 
        @profile = Profile.new 
    end 

    def create
       
        @profile = Profile.create(profile_params)
        @profile.user_id = current_user.id
        if @profile.save 
          flash[:notice] = "You created your User Profile successfully"
          redirect_to user_path(@profile.user)
        else
          flash[:notice] = "Unable to create your User Profile."
          
            render 'profiles/new'
        end 
    end 

    def show
      @profile = Profile.find(params[:id])
    end 

    private 

    def profile_params
        params.require(:profile).permit(:username, :age, :ethnicity, 
        :sexorientation, :nationality, :gender, :employed, :bio)
    
    end 
    

end 

app/views/profiles/_form.html.erb
<h2>User Profile</h2>

<%= form_for :profile, url: user_profiles_path do |f| %>
  
    <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username %>
    </div>
    <div class="field">
        <%= f.label :ethnicity %><br />
        <%= f.select :ethnicity, %w{African/African-descended European/European-descended NativeAmerican/FirstNations Latinx Asian/Asian-descended Multi-Ethnic}, :prompt => 'Select', required: true, placeholder: 'Gender' %>
    </div>

    <div class="field">
        <%= f.label :gender %><br />
        <%= f.select :gender, %w{Woman Man Transgender NonBinary Other }, :prompt => 'Select', required: true %>
    </div>
    
    <div class="field">
        Sexual Orientation<% f.label :sexorientation %><br />
        <%= f.select :sexorientation, %w{Straight Lesbian Gay Bisexual Pansexual Asexual Queer Other }, :prompt => 'Select', required: true %>
    </div>

    <div class="field">
        <%= f.label :nationality %><br />
        <%= f.select :nationality, %w{American Other }, :prompt => 'Select', required: true %>
    </div>

    <div class="field">
        <%= f.label :age %><br />
        <%= f.number_field :age %>
    </div>

    <div class="field">
        <%= f.label :bio %><br />
        <%= f.text_area :bio %>
    </div>

    <div class="field">
        <%= f.label :employed %><br />
        <%= f.check_box :employed %>
    </div>
    
    <%# <%= f.hidden_field :user_id, value: @user.id %>

        <div class="actions">
            <%= f.submit "Create" %>
        </div>
        <% end %>

    <% if @profile.errors.any? %>
    <div class ="field_with_errors">
        <ul class="Signup_Errors">
        <% for message_error in @profile.errors.full_messages %>
        <li>* <%= message_error %></li>
        <% end %>
        </ul>
    <% end %>

app/views/profiles/new.html.erb
<%= render "form" %>