config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  resources :companies do
    resources :reviews, only: [:new, :create, :show, :destroy]
     
  end 
  
  resources :reviews do
    resources :thanks, only: [:new, :create]
  end

  resources :reviews do
    resources :comments, only: [:new, :create]
  end

  resources :user_companies

  resources :users do 
    resources :user_companies, only: [:show, :new, :create]
  end 

  resources :users do 
    resources :profiles, only: [:show, :new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_companies
  has_many :companies, through: :user_companies
  accepts_nested_attributes_for :user_companies, allow_destroy: true
  

  
  has_one :profile 
  accepts_nested_attributes_for :profile, allow_destroy: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']
        ['extra']['raw_info']
        user.email = datat['email'] if user.email.blank?
      end 
    end 
  end 

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end 



        
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def facebook
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication 
            set_flash_message(:notice, :success, :kind => 'Facebook') if
            is_navigational_format?
        else
            session['devise.facebook_data'] = request.env['omniauth.auth']
            redirect_to new_user_registration_url
        end 
    end 

    def failure
        redirect_to root_path
    end 

    private

    def user_params
        params.require(:user).permit(company_id:[])
    end 

end 

app/controllers/users_controller.rb
class UsersController<ApplicationController

    def show
        @user = User.find(params[:id])
    end 

    

   
    
end

app/views/users/show.html.erb
<h1> 
    <% if !@user.profile.username.nil? %>
        <%= @user.profile.username %> 
    <% else %> 
        <%= @user.name%>
<% end %> </h1>

 

<h2> Work Experience </h2>
    <% @user.user_companies.each do |uc| %>
        <p> <%=link_to uc.company.name,  company_path(uc)%> <%= uc.year %> 
    <%= (uc.year) == 1 ? 'year' : 'years'%> <%= link_to "Delete", uc, method: :delete, data: { confirm: "You sure?" } %></p>
    <% end %> <br>

<h2> About Me </h2>
<% if @user.profile.nil? %>
    <p> This user has not created a User Profile</p>
<% else %> <% end %>
    <p>Gender: <%= @user.profile.gender %></p>
    <br>
    <p>Ethnicity: <%= @user.profile.ethnicity %></p>
    <br>
    <p>Sexual Orientation: <%= @user.profile.sexorientation %></p>
    <br>
    <p>Nationality: <%= @user.profile.nationality %></p>
    <br>
    <p>A little bit about them: <%= @user.profile.bio %></p>
    <br>
    <p>Currently Employed? <%= @user.profile.employed %></p>
    <br>


    <p> Want to learn more about <%=@user.profile.username%>'s experiences? Copy their address below, shoot them an email, and start the conversation. </p>
    <p><%= @user.email %></p>


<%= link_to "Go Home", companies_path %>