config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  resources :companies do
    resources :reviews, only: [:new, :create, :show, :destroy]
     
  end 
  
  resources :reviews do
    resources :thanks, only: [:new, :create]
  end

  resources :reviews do
    resources :comments, only: [:new, :create]
  end

  resources :user_companies

  resources :users do 
    resources :user_companies, only: [:show, :new, :create]
  end 

  resources :users do 
    resources :profiles, only: [:show, :new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :user_companies
    has_many :users, through: :user_companies
    has_many :reviews, dependent: :destroy
    accepts_nested_attributes_for :reviews
   
    validates :name, presence: true, uniqueness: true
    validates :headquarters, presence: true
    validates :industry, presence: true 
    validates :revenue, presence: true 
    validates :mission_motto_ideal, presence: true 
    validates :website, uniqueness: true 
    
end

app/controllers/companies_controller.rb
class CompaniesController<ApplicationController

    def new
        @company = Company.new
    end 

    def index
        @current_user = current_user
        @companies = Company.all
    end
    
    def create
        @company = Company.create(company_params)
       
        if @company.save
            flash[:notice] = "Company created successfully"
            redirect_to company_path(@company)
        else 
            flash[:notice] = 'Unable to save this company'
            render 'companies/new'
        end 
    end

    def show
        @company = Company.find(params[:id])
    end 

    def destroy
        @company = Company.find(params[:id])
        @company.destroy
        flash[:success] = 'Company deleted'
        redirect_to companies_path
    end 

    private

    def company_params
        params.require(:company).permit(:name, :headquarters, :industry, :number_of_employees, :revenue,
        :mission_motto_ideal, :publicly_owned, :website)
    end 
end

app/views/companies/_form.html.erb
<h2>Submit a new Company</h2>

<%= form_for(@company) do |f| %>
    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :headquarters %><br />
        <%= f.text_field :headquarters %>
    </div>

    <div class="field">
        <%= f.label :industry %><br />
        <%= f.select :industry, 
        %w{Agriculture Apparel/Fashion Animals/Pets Manufacturing Electronics Pharmaceuticals Food Telecommunications Energy Media Medicine Music Education Film Software/Technology }, :prompt => 'Select', required: true, placeholder: 'Industry' %>  
    </div>

    <div class="field">
        Number of Employees<% f.label :number_of_employees %><br />
        <%= f.select :number_of_employees,
        %w{1-50 51-99 100-499 500-999 1000+ 10K+ } %>
    </div>

    <div class="field">
        <%= f.label :revenue %><br />
        <%= f.select :revenue, %w{ <$5M $5M-$10M $10M-$1B $1B-$5B $5B+ }, :prompt => 'Select', required: true, placeholder: 'Revenue' %>
    </div>

    <div class="field">
        Publicly owned company? <% f.label :publicly_owned %><br />
        <%= f.check_box :publicly_owned %>
    </div>


    <div class="field">
        <%= f.label :website %><br />
        <%= f.text_field :website %>
    </div>

    <div class="field">
        Does this company have a mission statement, motto, or core values? Please share below.
        <% f.label :mission_motto_ideal %><br />
        <%= f.text_area :mission_motto_ideal %>
    </div>

    <% f.label :user %>
    <%= collection_select(:company, :user_ids, User.all, :id, 
        :name, {:selected => @company.user_ids, :include_blank => true }, { :multiple => false } )%>


  <br>
  <br>
    <div class="actions">
        <%= f.submit "Submit company profile" %>
    </div>
<% end %>

    <% if @company.errors.any? %>
        <div class ="field_with_errors">
        <ul class="Submission_Errors">
        <% for message_error in @company.errors.full_messages %>
        <li>* <%= message_error %></li>
    <% end %>
<% end %>    

app/views/companies/index.html.erb
<% if !current_user.image.nil? %>
    <%= image_tag(current_user.image) %>
  <% end %>

<% if !current_user.profile.nil? %>
  <%= link_to 'View your profile', user_path(current_user)%>
  <% end %>

<% if current_user.profile.nil? %>
<p> Please create a <%= link_to 'User Profile', new_user_profile_path(current_user)%>! </p>
   
  <% end %>

<br>
    
    

<h2 style='margin-top:100px;font-size:2rem'>Search for a company below, or submit one yourself.</h2>

<% @companies.each do |company| %>
  <h1 style='font-size:1.5rem;margin-top:50px'>
      <%=link_to company.name,  company_path(company)%>:
       <% if company.reviews.blank? %>
 <p>This company has not been rated or reviewed yet.</p>  
 <% else %> 
<%=company.reviews.average(:rating)%> stars</h1> 
      
       <% end %>
   <p>Website: <%= company.website %></p>
   <p>Headquarters: <%= company.headquarters %></p>
   <p>Annual Revenue: <%= company.revenue %></p>
   <p>Mission, Motto, or Ideals: <%= company.mission_motto_ideal%></p>
   <br>
   <br>
   
 
  <% end %>
  


<%= link_to "Don't see a company you're looking for? Submit a new company.", new_company_path %>
<br>
<%= link_to 'Logout', destroy_user_session_path, method: :delete%>

app/views/companies/new.html.erb
<%= render "form" %>

app/views/companies/show.html.erb
<%= link_to "Add employment with this company", new_user_company_path(company_id: @company.id) %>

<h1 style='margin-top:100px;font-size:2rem'><%= @company.name %></h1>
 
    <p><%= @company.reviews.average(:rating)%> stars</p> 
    <p>Website: <%= @company.website %></p>
    <p>Headquarters: <%= @company.headquarters %></p>
    <p>Industry: <%= @company.industry %></p>
    <p>Number of Employees: <%= @company.number_of_employees %></p>
    <p>Revenue: <%= @company.revenue %></p>
    <p>Publicly Owned: <%= @company.publicly_owned %></p>
    <p>Mission Statement or Motto: <%= @company.mission_motto_ideal %></p>
<br>
 <p> Check out what other people had to say: </p> 
<ul> 
 <% @company.reviews.each do |review| %>
<li><%= link_to review.title,  review_path(review) %>
(<%=review.rating%> <%= (review.rating) == 1 ? 'Star' : 'Stars' %>) </li>
<p> <%= review.thanks.count%> <%= (review.rating) == 1 ? 'thank' : 'thanks' %>, 
<%= review.comments.count%> <%= (review.rating) == 1 ? 'comment' : 'comments' %>
<br>

 <% end %>
 </ul>



 <%= link_to "Want to submit a review of this company? Click here.", new_company_review_path(@company) %>
<br>
<br>
<%= link_to "Delete Company", @company, method: :delete, data: { confirm: "You sure?" } %>
<br>
<%= link_to "Check out other companies.", companies_path %>
<br>
<br>
<br>
<%= link_to 'Logout', destroy_user_session_path, method: :delete%>