config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  resources :companies do
    resources :reviews, only: [:new, :create, :show, :destroy]
     
  end 
  
  resources :reviews do
    resources :thanks, only: [:new, :create]
  end

  resources :reviews do
    resources :comments, only: [:new, :create]
  end

  resources :user_companies

  resources :users do 
    resources :user_companies, only: [:show, :new, :create]
  end 

  resources :users do 
    resources :profiles, only: [:show, :new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    include ::ReviewsHelper
    before_action :logged_in?, only: [:create]
    before_action :employed_here?, only: [:new, :create]
    
    def new
      @review = Review.new 
    end 

    def index
      @reviews = Review.all(review_params[:company_id]) 
    end

    def show
      @company = Company.find_by(id: params[:id])
      @review = Review.find_by(id: params[:id])
    end

    def create
      @review = Review.create(review_params)
      @review.user_id = current_user.id
      @review.company_id = params[:company_id]
      if @review.save
        redirect_to company_path(@review.company)
      else 
        flash[:notice] = "Review not saved."
        render 'new'
      end 
    end

   
    
    
    private

      def review_params
        params.require(:review).permit(:rating, :content, :title, :company_id)
      end 

      def company_params
        params.require(:company).permit(:name, :headquarters, :industry, :sizeNumberofEmployees, :revenue, 
        :mission_motto_ideal, :publicly_owned, :website)
      end 

end 

app/views/reviews/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :review, url: company_reviews_path do |f| %> 
    <% if @review.errors.any? %>
  <div class ="field_with_errors">
    <h2>
      <%= pluralize(@review.errors.count, "error") %>
      prohibited this review from being saved:
    </h2>
 
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li> 
    <% end %>
    </ul>
  <div>
<% end %>

      <p>Please rate 1-5 stars. (1 being "poor" and 5 being "excellent")
        <% f.label :rating %>
        <%= f.number_field :rating %></p>

      <p> Please title your review, so other users can find it! 
      <% f.label :title %>
      <%= f.text_field :title%></p>

      <p> Tell us how you feel. 
      <% f.label :content %>
      <%= f.text_area :content %></p>

      <%= f.submit "Submit review" %>
    <% end %>

   
  </div>
</div>

app/views/reviews/new.html.erb
<h1 style='margin-top:100px;font-size:2rem'>Write a review below:</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<h1> <%= @review.title %>
(<%= @review.rating  %>
<%= (@review.rating) == 1 ? 'Star' : 'Stars' %>)</h1>

<h3><%= @review.content %> <%= @review.created_at %> </h3>

<p><%= @review.thanks.count %> <%= (@review.thanks.count) == 1 ? 'Thank' : 'Thanks'%> </p>  
<p><%= button_to 'Thank', review_thanks_path(@review), method: :post %>
<%= button_to "Comment", new_review_comment_path(@review), method: :get %></p>
<br>
<br>


<h3> Comments: </h3>
 <% @review.comments.each do |comment| %>
    <br> <%=comment.user.name %>:
    <%=comment.content %><br> 
     <%end %> 


<br>
<br>
<p> Go back to <%= link_to @review.company.name, company_path(@review.company)  %>
<%= link_to "Check out other companies.", companies_path %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete%>